name: EPAC AVNM Deployment

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'avnm/**'
  workflow_dispatch:

jobs:
  detect-tenants:
    name: Detect changed tenants
    runs-on: ubuntu-latest
    outputs:
      tenants: ${{ steps.set-matrix.outputs.tenantMatrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^avnm/' | cut -d '/' -f2 | sort -u | uniq)
          matrix=$(echo "$changed" | jq -R . | jq -cs .)
          echo "tenantMatrix={\"tenant\": $matrix}" >> $GITHUB_OUTPUT

  plan:
    needs: detect-tenants
    strategy:
      matrix: ${{ fromJson(needs.detect-tenants.outputs.tenants) }}
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: env-${{ matrix.tenant }}
      planGitHubEnvironment: env-${{ matrix.tenant }}-plan
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./avnm/${{ matrix.tenant }}
    secrets: inherit

  deploy:
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && github.ref == 'refs/heads/main'
    strategy:
      matrix: ${{ fromJson(needs.detect-tenants.outputs.tenants) }}
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: env-${{ matrix.tenant }}
      planGitHubEnvironment: env-${{ matrix.tenant }}-deploy
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./avnm/${{ matrix.tenant }}
    secrets: inherit