name: EPAC AVNM Deployment

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'avnm/**'
  workflow_dispatch:

jobs:
  detect-tenants:
    name: Detect changed tenants
    runs-on: ubuntu-latest
    outputs:
      tenants: ${{ steps.set-matrix.outputs.tenantMatrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Ensure jq is available
        run: sudo apt-get update && sudo apt-get install -y jq

      - id: set-matrix
        run: |
          echo "Detecting changed tenants..."

          changed=$(git diff --name-only ${{ github.event.before || 'HEAD~1' }} ${{ github.sha }} | grep '^avnm/' | cut -d '/' -f2 | sort -u | uniq)

          if [[ -z "$changed" ]]; then
            echo "No changes detected, using all tenants under avnm/"
            changed=$(find avnm -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
          fi

          echo "Changed tenants:"
          echo "$changed"

          matrix=$(echo "$changed" | jq -R . | jq -cs .)
          echo "tenantMatrix={\"tenant\": $matrix}" >> $GITHUB_OUTPUT

  plan:
    needs: detect-tenants
    strategy:
      matrix: ${{ fromJson(needs.detect-tenants.outputs.tenants) }}
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: env-${{ matrix.tenant }}
      planGitHubEnvironment: env-${{ matrix.tenant }}-epac-plan
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./avnm/${{ matrix.tenant }}
    secrets: inherit

  deploy:
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && github.ref == 'refs/heads/main'
    strategy:
      matrix: ${{ fromJson(needs.detect-tenants.outputs.tenants) }}
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: env-${{ matrix.tenant }}
      planGitHubEnvironment: env-${{ matrix.tenant }}-epac-deploy
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./avnm/${{ matrix.tenant }}
    secrets: inherit
