# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Thoor Security Tenant Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'policy*/**'
  workflow_dispatch:

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan tenant
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: env-thoor-security
      planGitHubEnvironment: env-thoor-security-epac-plan
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./
    secrets: inherit

  deployPolicy:
    name: Deploy tenant Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: env-thoor-security
      planGitHubEnvironment: env-thoor-security-epac-deploy-policy
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./
    secrets: inherit

  #deployRoles:
  #  name: Deploy tenant Role Changes
  #  needs: [plan, deployPolicy]
  #  if: needs.plan.outputs.deployRoleChanges == 'yes' && github.ref == 'refs/heads/main'
  #  uses: ./.github/workflows/deploy-roles.yml
  #  with:
  #    pacEnvironmentSelector: env-mg
  #    planGitHubEnvironment: env-mg-epac-deploy-roles
  #    PAC_INPUT_FOLDER: ./Output
  #    PAC_DEFINITIONS_FOLDER: ./
  #  secrets: inherit